export const ABILITIES = [
    { value: "CLEANING", label: "청소" },
    { value: "COOKING", label: "요리" },
    { value: "DRIVING", label: "운전" },
    { value: "CHILD_CARE", label: "아이 돌봄" },
    { value: "PET_CARE", label: "반려동물 돌봄" },
    { value: "HANDY_MAN", label: "간단한 수리 & 허드렛일 가능" },
    { value: "TRANSLATION", label: "번역 / 통역" },
    { value: "PHOTOGRAPHY", label: "사진 / 영상 촬영" },
    { value: "TYPING", label: "빠른 타이핑" },
    { value: "PUNCTUALITY", label: "시간 엄수" },
    { value: "TEAM_WORK", label: "팀워크" },
    { value: "FAST_LEARNING", label: "빠른 학습 능력" },
    { value: "COMMUNICATION", label: "의사소통 능력" },
    { value: "RESPONSIBILITY", label: "책임감" },
    { value: "FRIENDLY", label: "친절함" },
    { value: "MULTI_TASKING", label: "멀티태스킹 가능" },
    { value: "ATTENTION_TO_DETAIL", label: "꼼꼼함" },
    { value: "DRIVER_LICENSE", label: "운전면허증 보유" },
    { value: "FOOD_SAFETY_CERT", label: "식품 위생 관련 자격증" },
    { value: "CHILD_CARE_CERT", label: "보육 관련 자격증" },
    { value: "PET_CARE_CERT", label: "반려동물 돌봄 관련 자격증" },
    { value: "SECURITY_CERT", label: "보안 관련 자격증" },
  ];
  